import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Separator } from "@/components/ui/separator";
import Footer from "@/components/footer";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QpiAI Pro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interFont.variable} antialiased bg-white`}>
        <Navbar />
        {children}
        <Separator className="my-4" />
        <Footer></Footer>
      </body>
    </html>
  );
}
